/* Write your T-SQL query statement below */

/* Write your T-SQL query statement below */
SELECT DISTINCT C.EXPERIENCE, ISNULL (accepted_candidates, 0)  AS accepted_candidates
FROM CANDIDATES C
LEFT OUTER JOIN
(SELECT  EXPERIENCE ,  COUNT (SF) AS accepted_candidates FROM
(SELECT EXPERIENCE , SUM (SALARY) OVER (ORDER BY EXPERIENCE DESC, SALARY ) AS SF FROM
(SELECT EXPERIENCE, SALARY, SL
FROM
(SELECT EXPERIENCE , SALARY ,
SUM (SALARY) OVER (ORDER BY EXPERIENCE DESC, SALARY ) AS SL
FROM CANDIDATES ) T1 
WHERE (EXPERIENCE = 'Senior' AND SL <=  70000 ) OR  EXPERIENCE  = 'Junior')   T2  ) T3 
WHERE SF <= 70000
GROUP BY EXPERIENCE ) T4
ON C.EXPERIENCE = T4.EXPERIENCE

